replicaCount: 2
image:
  repository: registry.hcloud.hmc.co.kr/ccs/ccsp20-behavioral
  pullPolicy: IfNotPresent
  tag: "1.0.9"

# Resource quota
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

# Readiness 
readinessInitialDelaySeconds: 30
readinessPeriodSeconds: 30

# Liveness
livenessInitialDelaySeconds: 30
livenessPeriodSeconds: 30

# JVM Option
jvm:
  enabled: false
  option: ""

# Service 
service:
  type: NodePort
  port: 8080
  nodePort: 30041
# Ingress 
ingress:
  enabled: false
  host: 

# AutoScaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Delievery Policy
autoPromotionEnabled: true

