image:
  repository: registry.hcloud.hmc.co.kr/ccs/ccsp20-behavioral
  pullPolicy: IfNotPresent
  tag: "1.0.21"

# Resource quota
resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 1000m
    memory: 2Gi


# Readiness 
readinessInitialDelaySeconds: 30
readinessPeriodSeconds: 30

# Liveness
livenessInitialDelaySeconds: 60
livenessPeriodSeconds: 30

# JVM Option
jvm:
  enabled: true
  option: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:InitialRAMPercentage=50 -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=75"

# Service 
service:
  type: ClusterIP
  port: 8080
  ipamRange: 
  loadbalancerIP: 

# AutoScaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

# TimeZone
timezone: Asia/Seoul

# Delievery Policy
autoPromotionEnabled: true

# Injetct Config server
configServer:
  enabled: true

rolloutName: behavior-az2-prd