server:
  tomcat:
    threads:
      max: 500000
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: ccsp20-behavioralpatternanalysis

---
#default config
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
  async:
    core-pool-size: 200
    max-pool-size: 3200
    queue-capacity-size: 1
    keep-allive-secound: 15
  zipkin:
    base-url: http://10.11.53.1:9411
    httptag: true
  kafka:
    bootstrap-servers: 10.7.159.122:9092, 10.7.159.123:9092, 10.7.159.124:9092, 10.7.159.125:9092, 10.7.159.126:9092

#feign client config
feign:
  httpclient:
    enabled: true
    max-connections: 200000
    max-connections-per-route: 150000
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 122000
        loggerLevel: FULL
        retryer: com.hkmc.behavioralpatternanalysis.config.feign.FeignClientRetryer

#logback config
logging:
  level:
    root: INFO
    com.hkmc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.apache.kafka: ERROR
    io.micrometer.core.instrument.binder.kafka.KafkaMetrics: ERROR

transaction:
  logger:
    exclude:
      url: cloudfoundryapplication, swagger

#DSP server info
dsp:
  header.auth: Basic MTVlYWMyNmItNWIwOC00MDc1LWI5NDktN2Q5YzBhMzg5MTc2OkFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5MEhLTUNJQ1REU1A0NA==
  server:
    common.uri: /api/v1/dsp/ubi
    bluelink:
      url: http://10.11.60.218:6101
      name: BlueLink
    uvo:
      url: http://10.11.60.218:6101
      name: UVO
    genesis:
      url: http://10.11.60.218:6101
      name: GenesisConnected

validation:
  check: true

---
#spring actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
