server:
  tomcat:
    threads:
      max: 500000
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: ccsp20-behavioralpatternanalysis

---
#default config
spring:
  profiles: local
  async:
    core-pool-size: 200
    max-pool-size: 3200
    queue-capacity-size: 1
    keep-allive-secound: 15
  zipkin:
    base-url: http://10.11.53.1:9411
    httptag: true
  mtgateway:
    server:
      url: http://localhost:9001
      name: mtgateway
  redis:
    host: "10.11.39.67"
    port: 38913
    password: "a206339c-2eef-4bb1-bdfb-019a7df9c443"
  postgres:
    uri: "10.20.213.192"
    port: 5432
    database: "megazone"
    username: "megazone"
    password: "megazone"
    pool:
      name: "customPool"
      maxidletime: 100
      maxlifetime: 100
      initalsize: 10
      max-size: 100
      maxcreateconnectiontime: 10000

#feign client config
feign:
  httpclient:
    enabled: true
    max-connections: 200000
    max-connections-per-route: 150000
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 122000
        loggerLevel: FULL
        retryer: com.hkmc.behavioralpatternanalysis.config.feign.FeignClientRetryer

#logback config
logging:
  level:
    root: INFO
    com.hkmc: DEBUG
    org.springframework.data.r2dbc: DEBUG

#DSP server info
dsp:
  header.auth: Basic MTVlYWMyNmItNWIwOC00MDc1LWI5NDktN2Q5YzBhMzg5MTc2OkFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMTIzNDU2Nzg5MEhLTUNJQ1REU1A0NA==
  server:
    common.uri: /api/v1/dsp/ubi
    bluelink:
      url: http://10.11.60.218:6101
      name: BlueLink
    uvo:
      url: http://10.11.60.218:6101
      name: UVO
    genesis:
      url: http://10.11.60.218:6101
      name: GenesisConnected

---
#spring actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"
