apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "behavioral.fullname" . }}
  labels:
    app: {{ template "behavioral.name" . }}
    chart: {{ template "behavioral.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "behavioral.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "behavioral.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app: {{ template "behavioral.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: environment
            - name: spring.config.import
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: configserver
            - name: spring.cloud.config.name
              value: ccsp20-common,ccsp20-behavioral
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
  strategy:
    blueGreen:
      activeService: behavioral
      previewService: behavioral-blue
      autoPromotionEnabled: {{ .Values.autoPromotionEnabled }}