apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "behavior.fullname" . }}
  labels:
    app: {{ template "behavior.name" . }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "behavior.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "backend"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "behavior.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "behavior.name" . }}
        release: {{ .Release.Name }}
        app.kubernetes.io/name: {{ template "behavior.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: "backend"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: environment
            - name: spring.config.import
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: configserver
            - name: spring.cloud.config.name
              value: ccsp20-common,ccsp20-behavioral
            {{- if .Values.jvm.enabled }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.jvm.option }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: {{ .Values.livenessInitialDelaySeconds}}
            periodSeconds: {{ .Values.livenessPeriodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: {{ .Values.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.readinessPeriodSeconds }}
  strategy:
    blueGreen:
      activeService: behavior
      previewService: behavior-blue
      autoPromotionEnabled: {{ .Values.autoPromotionEnabled }}