apiVersion: v1
kind: Service
metadata:
  name: behavioral
  labels:
    app: {{ template "behavioral.name" . }}
    chart: {{ template "behavioral.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "behavioral.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: behavioral-blue
  labels:
    app: {{ template "behavioral.name" . }}
    chart: {{ template "behavioral.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "behavioral.name" . }}
    release: {{ .Release.Name }}